### ISSUE TITLE
add optgroups to group second-level links

### ISSUE THREAD

**Issue by zomigi** [mattkersley/Responsive-Menu#10]
It would be cool/more semantic/more accessible to add optgroups to group together the related second-level links, rather than just visually indenting them. It could work like this:

The list (can't get Github list markup to work, sorry!):
1. Vegetables
2. Fruit
2a. Apples
2b. Bananas
2c. Oranges

The select:

`````` <select>
      <optgroup label="Vegetables">
        <option>Vegetables main page</option>
      </optgroup>
      <optgroup label="Fruit">
        <option>Fruit main page</option>
        <option>Apples</option>
        <option>Bananas</option>
        <option>Oranges</option>
      </optgroup>
    </select>```
``````

**Comment by mattkersley** [comment]
Added in V2 branch.

Not ready for release yet, but it's there ;-)
