### ISSUE TITLE
Multiple Menus

### ISSUE THREAD

**Issue by bryoz** [mattkersley/Responsive-Menu#13]
Hi there,

Firstly, thanks for this function. I've found it of great use for responsive navigation.

I'd like to ask if there is a simple way to have more than one menu in a page, displaying separate lists. Is this possible using the code as it is? 

Regards,
Bry

**Comment by mattkersley** [comment]
Hi.

Yes, this is possible.

You can change the "combine" option to false to leave each list as a separate dropdown.

e.g.
$('css-selector').mobileMenu({combine:false});

Let me know if you need any more help.

**Comment by bryoz** [comment]
That's great, thanks!
