### ISSUE TITLE
Consider adding a license

### ISSUE THREAD

**Issue by redndahead** [mattkersley/Responsive-Menu#20]
While I appreciate your intentions of trying to get your code out to the widest range of audiences, unfortunately not having a license makes things more complicated for the people who care.  If you would like to make your software available to the widest range of groups I would suggest using the MIT license. http://opensource.org/licenses/mit-license.php When you don't add a license it is subject to the copyright rules of the country you created it in which may be incompatible with other licenses.  In the case of the US it's all rights reserved which means you must specifically give permission for people to use your software.
Something else to read: http://www.codinghorror.com/blog/2007/04/pick-a-license-any-license.html

**Comment by krisbulman** [comment]
+1 MIT & GPL or Unlicense

**Comment by mattkersley** [comment]
used unlicense.
