### ISSUE TITLE
How to style the 'select' menu using CSS?

### ISSUE THREAD

**Issue by Mona123** [mattkersley/Responsive-Menu#27]
It is actually not an issue or maybe I'm doing wrong way, not sure, so posting here.

I have tried but not working for me. I'm trying to style the 'select dropdown menu' like here (for smaller screen)
http://bavotasan.com/2011/style-select-box-using-only-css/

Any help will be highly appreciated.

thanks!

**Comment by mattkersley** [comment]
You should be able to style the select menu in the same way you can any others.

There are plenty of tutorials around the web explaining how to do this.
