### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by BrookeDot** [mattkersley/Responsive-Menu#30]
Hi Matt, 

I know you say that this plugin doesn't have a license but might I suggest you add one. If yo really don't care what people do you can add the "Do What the Fuck You Want to Public License" http://www.wtfpl.net/

This basically just ensures others that they can use your code :)

**Comment by rohitink** [comment]
Yes, I would really recommend the WTFPL or a GPL license.

**Comment by mattkersley** [comment]
https://github.com/mattkersley/Responsive-Menu/blob/master/license
