### ISSUE TITLE
iOS does not respect &nbps; spaces

### ISSUE THREAD

**Issue by iamdustan** [mattkersley/Responsive-Menu#5]
iOS does not respect sub-level &nbsp; spaces. (Running v4.3.4).

I tested an Android device (no idea which one), and the spaces were rendered properly.

**Comment by mattkersley** [comment]
I noticed this.

I'm planning to add <optgroup> support at some point.

I also plan to add the ability to merge menu's.
If you have a utility menu and a main menu, you won't want both separately on a mobile screen.

Time is tight at the moment though, so not sure when I will get round to that.

**Comment by iamdustan** [comment]
Sounds good. I'm going to run a forked version for a bit and add the optgroup.

Also, I want to add the ability to pass in a configuration on how deep the select box should go. On the site I'm developing, showing child and grandchild menu items in a mobile select box is overwhelming.

**Comment by iamdustan** [comment]
I should've seen this coming. Nested Optgroups.

Have you given any thought on how to solve 3rd level menu items?

I think going that deep will create a terribel UX in a dropdown list; but perhaps providing another way to access deeper menu items would be useful?

**Comment by mattkersley** [comment]
I agree, the UX would be rubbish.
I haven't had any free time to look into anything yet (and probably wont this week)... 

Maybe upon selecting a second level item, a new dropdown could appear with the third level items?
This could get messy though... other than that, I have no other ideas at the moment.

**Comment by iamdustan** [comment]
That was my idea as well, but at that point I think switching to a mobile app menu style would make more sense. Select and item and then the rest of the items come back in.

I'm going to ignore that problem for now. The fork request I just sent you solves the problem I have. Maybe I'll add it to go two levels deep and optgroup the second level and not worry about third level. Menu's that deep are rubbish on desktop, too.
